package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AffectationDemandeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationDemandeAllPropertiesEquals(AffectationDemande expected, AffectationDemande actual) {
        assertAffectationDemandeAutoGeneratedPropertiesEquals(expected, actual);
        assertAffectationDemandeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationDemandeAllUpdatablePropertiesEquals(AffectationDemande expected, AffectationDemande actual) {
        assertAffectationDemandeUpdatableFieldsEquals(expected, actual);
        assertAffectationDemandeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationDemandeAutoGeneratedPropertiesEquals(AffectationDemande expected, AffectationDemande actual) {
        assertThat(actual)
            .as("Verify AffectationDemande auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationDemandeUpdatableFieldsEquals(AffectationDemande expected, AffectationDemande actual) {
        assertThat(actual)
            .as("Verify AffectationDemande relevant properties")
            .satisfies(a -> assertThat(a.getDateAffectation()).as("check dateAffectation").isEqualTo(expected.getDateAffectation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAffectationDemandeUpdatableRelationshipsEquals(AffectationDemande expected, AffectationDemande actual) {
        assertThat(actual)
            .as("Verify AffectationDemande relationships")
            .satisfies(a -> assertThat(a.getDemande()).as("check demande").isEqualTo(expected.getDemande()))
            .satisfies(a -> assertThat(a.getPartenaire()).as("check partenaire").isEqualTo(expected.getPartenaire()));
    }
}
