package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static sn.orange.conciergerie.domain.AssertUtils.bigDecimalCompareTo;

public class CodePromoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodePromoAllPropertiesEquals(CodePromo expected, CodePromo actual) {
        assertCodePromoAutoGeneratedPropertiesEquals(expected, actual);
        assertCodePromoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodePromoAllUpdatablePropertiesEquals(CodePromo expected, CodePromo actual) {
        assertCodePromoUpdatableFieldsEquals(expected, actual);
        assertCodePromoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodePromoAutoGeneratedPropertiesEquals(CodePromo expected, CodePromo actual) {
        assertThat(actual)
            .as("Verify CodePromo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodePromoUpdatableFieldsEquals(CodePromo expected, CodePromo actual) {
        assertThat(actual)
            .as("Verify CodePromo relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a ->
                assertThat(a.getValeur()).as("check valeur").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getValeur())
            )
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFin()).as("check dateFin").isEqualTo(expected.getDateFin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodePromoUpdatableRelationshipsEquals(CodePromo expected, CodePromo actual) {
        // empty method
    }
}
