package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CodeQrServiceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodeQrServiceAllPropertiesEquals(CodeQrService expected, CodeQrService actual) {
        assertCodeQrServiceAutoGeneratedPropertiesEquals(expected, actual);
        assertCodeQrServiceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodeQrServiceAllUpdatablePropertiesEquals(CodeQrService expected, CodeQrService actual) {
        assertCodeQrServiceUpdatableFieldsEquals(expected, actual);
        assertCodeQrServiceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodeQrServiceAutoGeneratedPropertiesEquals(CodeQrService expected, CodeQrService actual) {
        assertThat(actual)
            .as("Verify CodeQrService auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodeQrServiceUpdatableFieldsEquals(CodeQrService expected, CodeQrService actual) {
        assertThat(actual)
            .as("Verify CodeQrService relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getQrCode()).as("check qrCode").isEqualTo(expected.getQrCode()))
            .satisfies(a -> assertThat(a.getDateGeneration()).as("check dateGeneration").isEqualTo(expected.getDateGeneration()))
            .satisfies(a -> assertThat(a.getDateExpiration()).as("check dateExpiration").isEqualTo(expected.getDateExpiration()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodeQrServiceUpdatableRelationshipsEquals(CodeQrService expected, CodeQrService actual) {
        assertThat(actual)
            .as("Verify CodeQrService relationships")
            .satisfies(a -> assertThat(a.getDemande()).as("check demande").isEqualTo(expected.getDemande()));
    }
}
