package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static sn.orange.conciergerie.domain.AssertUtils.bigDecimalCompareTo;

public class CompteStockAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompteStockAllPropertiesEquals(CompteStock expected, CompteStock actual) {
        assertCompteStockAutoGeneratedPropertiesEquals(expected, actual);
        assertCompteStockAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompteStockAllUpdatablePropertiesEquals(CompteStock expected, CompteStock actual) {
        assertCompteStockUpdatableFieldsEquals(expected, actual);
        assertCompteStockUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompteStockAutoGeneratedPropertiesEquals(CompteStock expected, CompteStock actual) {
        assertThat(actual)
            .as("Verify CompteStock auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompteStockUpdatableFieldsEquals(CompteStock expected, CompteStock actual) {
        assertThat(actual)
            .as("Verify CompteStock relevant properties")
            .satisfies(a -> assertThat(a.getSolde()).as("check solde").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSolde()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompteStockUpdatableRelationshipsEquals(CompteStock expected, CompteStock actual) {
        assertThat(actual)
            .as("Verify CompteStock relationships")
            .satisfies(a -> assertThat(a.getService()).as("check service").isEqualTo(expected.getService()));
    }
}
