package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static sn.orange.conciergerie.domain.AssertUtils.bigDecimalCompareTo;

public class ConsommationQuotaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsommationQuotaAllPropertiesEquals(ConsommationQuota expected, ConsommationQuota actual) {
        assertConsommationQuotaAutoGeneratedPropertiesEquals(expected, actual);
        assertConsommationQuotaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsommationQuotaAllUpdatablePropertiesEquals(ConsommationQuota expected, ConsommationQuota actual) {
        assertConsommationQuotaUpdatableFieldsEquals(expected, actual);
        assertConsommationQuotaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsommationQuotaAutoGeneratedPropertiesEquals(ConsommationQuota expected, ConsommationQuota actual) {
        assertThat(actual)
            .as("Verify ConsommationQuota auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsommationQuotaUpdatableFieldsEquals(ConsommationQuota expected, ConsommationQuota actual) {
        assertThat(actual)
            .as("Verify ConsommationQuota relevant properties")
            .satisfies(a ->
                assertThat(a.getQuantite()).as("check quantite").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getQuantite())
            )
            .satisfies(a -> assertThat(a.getDateConsommation()).as("check dateConsommation").isEqualTo(expected.getDateConsommation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsommationQuotaUpdatableRelationshipsEquals(ConsommationQuota expected, ConsommationQuota actual) {
        assertThat(actual)
            .as("Verify ConsommationQuota relationships")
            .satisfies(a -> assertThat(a.getClient()).as("check client").isEqualTo(expected.getClient()))
            .satisfies(a -> assertThat(a.getQuotaService()).as("check quotaService").isEqualTo(expected.getQuotaService()))
            .satisfies(a -> assertThat(a.getQuotaDetail()).as("check quotaDetail").isEqualTo(expected.getQuotaDetail()));
    }
}
