package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CouverturePartenaireAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCouverturePartenaireAllPropertiesEquals(CouverturePartenaire expected, CouverturePartenaire actual) {
        assertCouverturePartenaireAutoGeneratedPropertiesEquals(expected, actual);
        assertCouverturePartenaireAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCouverturePartenaireAllUpdatablePropertiesEquals(CouverturePartenaire expected, CouverturePartenaire actual) {
        assertCouverturePartenaireUpdatableFieldsEquals(expected, actual);
        assertCouverturePartenaireUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCouverturePartenaireAutoGeneratedPropertiesEquals(CouverturePartenaire expected, CouverturePartenaire actual) {
        assertThat(actual)
            .as("Verify CouverturePartenaire auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCouverturePartenaireUpdatableFieldsEquals(CouverturePartenaire expected, CouverturePartenaire actual) {
        assertThat(actual)
            .as("Verify CouverturePartenaire relevant properties")
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFin()).as("check dateFin").isEqualTo(expected.getDateFin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCouverturePartenaireUpdatableRelationshipsEquals(CouverturePartenaire expected, CouverturePartenaire actual) {
        assertThat(actual)
            .as("Verify CouverturePartenaire relationships")
            .satisfies(a -> assertThat(a.getPartenaire()).as("check partenaire").isEqualTo(expected.getPartenaire()))
            .satisfies(a -> assertThat(a.getService()).as("check service").isEqualTo(expected.getService()));
    }
}
