package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EligibiliteServiceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEligibiliteServiceAllPropertiesEquals(EligibiliteService expected, EligibiliteService actual) {
        assertEligibiliteServiceAutoGeneratedPropertiesEquals(expected, actual);
        assertEligibiliteServiceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEligibiliteServiceAllUpdatablePropertiesEquals(EligibiliteService expected, EligibiliteService actual) {
        assertEligibiliteServiceUpdatableFieldsEquals(expected, actual);
        assertEligibiliteServiceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEligibiliteServiceAutoGeneratedPropertiesEquals(EligibiliteService expected, EligibiliteService actual) {
        assertThat(actual)
            .as("Verify EligibiliteService auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEligibiliteServiceUpdatableFieldsEquals(EligibiliteService expected, EligibiliteService actual) {
        assertThat(actual)
            .as("Verify EligibiliteService relevant properties")
            .satisfies(a -> assertThat(a.getAutorise()).as("check autorise").isEqualTo(expected.getAutorise()))
            .satisfies(a -> assertThat(a.getGratuit()).as("check gratuit").isEqualTo(expected.getGratuit()))
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFin()).as("check dateFin").isEqualTo(expected.getDateFin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEligibiliteServiceUpdatableRelationshipsEquals(EligibiliteService expected, EligibiliteService actual) {
        assertThat(actual)
            .as("Verify EligibiliteService relationships")
            .satisfies(a -> assertThat(a.getService()).as("check service").isEqualTo(expected.getService()))
            .satisfies(a -> assertThat(a.getSegmentClient()).as("check segmentClient").isEqualTo(expected.getSegmentClient()))
            .satisfies(a -> assertThat(a.getTypeClient()).as("check typeClient").isEqualTo(expected.getTypeClient()));
    }
}
