package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EvaluationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationAllPropertiesEquals(Evaluation expected, Evaluation actual) {
        assertEvaluationAutoGeneratedPropertiesEquals(expected, actual);
        assertEvaluationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationAllUpdatablePropertiesEquals(Evaluation expected, Evaluation actual) {
        assertEvaluationUpdatableFieldsEquals(expected, actual);
        assertEvaluationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationAutoGeneratedPropertiesEquals(Evaluation expected, Evaluation actual) {
        assertThat(actual)
            .as("Verify Evaluation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationUpdatableFieldsEquals(Evaluation expected, Evaluation actual) {
        assertThat(actual)
            .as("Verify Evaluation relevant properties")
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()))
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()))
            .satisfies(a -> assertThat(a.getDateEvaluation()).as("check dateEvaluation").isEqualTo(expected.getDateEvaluation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEvaluationUpdatableRelationshipsEquals(Evaluation expected, Evaluation actual) {
        assertThat(actual)
            .as("Verify Evaluation relationships")
            .satisfies(a -> assertThat(a.getDemande()).as("check demande").isEqualTo(expected.getDemande()));
    }
}
