package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HistoriqueStatutDemandeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueStatutDemandeAllPropertiesEquals(HistoriqueStatutDemande expected, HistoriqueStatutDemande actual) {
        assertHistoriqueStatutDemandeAutoGeneratedPropertiesEquals(expected, actual);
        assertHistoriqueStatutDemandeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueStatutDemandeAllUpdatablePropertiesEquals(
        HistoriqueStatutDemande expected,
        HistoriqueStatutDemande actual
    ) {
        assertHistoriqueStatutDemandeUpdatableFieldsEquals(expected, actual);
        assertHistoriqueStatutDemandeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueStatutDemandeAutoGeneratedPropertiesEquals(
        HistoriqueStatutDemande expected,
        HistoriqueStatutDemande actual
    ) {
        assertThat(actual)
            .as("Verify HistoriqueStatutDemande auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueStatutDemandeUpdatableFieldsEquals(
        HistoriqueStatutDemande expected,
        HistoriqueStatutDemande actual
    ) {
        assertThat(actual)
            .as("Verify HistoriqueStatutDemande relevant properties")
            .satisfies(a -> assertThat(a.getDateChangement()).as("check dateChangement").isEqualTo(expected.getDateChangement()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueStatutDemandeUpdatableRelationshipsEquals(
        HistoriqueStatutDemande expected,
        HistoriqueStatutDemande actual
    ) {
        assertThat(actual)
            .as("Verify HistoriqueStatutDemande relationships")
            .satisfies(a -> assertThat(a.getDemande()).as("check demande").isEqualTo(expected.getDemande()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()));
    }
}
