package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IdempotencyKeyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdempotencyKeyAllPropertiesEquals(IdempotencyKey expected, IdempotencyKey actual) {
        assertIdempotencyKeyAutoGeneratedPropertiesEquals(expected, actual);
        assertIdempotencyKeyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdempotencyKeyAllUpdatablePropertiesEquals(IdempotencyKey expected, IdempotencyKey actual) {
        assertIdempotencyKeyUpdatableFieldsEquals(expected, actual);
        assertIdempotencyKeyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdempotencyKeyAutoGeneratedPropertiesEquals(IdempotencyKey expected, IdempotencyKey actual) {
        assertThat(actual)
            .as("Verify IdempotencyKey auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdempotencyKeyUpdatableFieldsEquals(IdempotencyKey expected, IdempotencyKey actual) {
        assertThat(actual)
            .as("Verify IdempotencyKey relevant properties")
            .satisfies(a -> assertThat(a.getCle()).as("check cle").isEqualTo(expected.getCle()))
            .satisfies(a -> assertThat(a.getTypeOperation()).as("check typeOperation").isEqualTo(expected.getTypeOperation()))
            .satisfies(a -> assertThat(a.getResourceId()).as("check resourceId").isEqualTo(expected.getResourceId()))
            .satisfies(a -> assertThat(a.getDateCreation()).as("check dateCreation").isEqualTo(expected.getDateCreation()))
            .satisfies(a -> assertThat(a.getDateExpiration()).as("check dateExpiration").isEqualTo(expected.getDateExpiration()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdempotencyKeyUpdatableRelationshipsEquals(IdempotencyKey expected, IdempotencyKey actual) {
        // empty method
    }
}
