package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class JournalAuditAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJournalAuditAllPropertiesEquals(JournalAudit expected, JournalAudit actual) {
        assertJournalAuditAutoGeneratedPropertiesEquals(expected, actual);
        assertJournalAuditAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJournalAuditAllUpdatablePropertiesEquals(JournalAudit expected, JournalAudit actual) {
        assertJournalAuditUpdatableFieldsEquals(expected, actual);
        assertJournalAuditUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJournalAuditAutoGeneratedPropertiesEquals(JournalAudit expected, JournalAudit actual) {
        assertThat(actual)
            .as("Verify JournalAudit auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJournalAuditUpdatableFieldsEquals(JournalAudit expected, JournalAudit actual) {
        assertThat(actual)
            .as("Verify JournalAudit relevant properties")
            .satisfies(a -> assertThat(a.getAction()).as("check action").isEqualTo(expected.getAction()))
            .satisfies(a -> assertThat(a.getTypeObjet()).as("check typeObjet").isEqualTo(expected.getTypeObjet()))
            .satisfies(a -> assertThat(a.getObjetId()).as("check objetId").isEqualTo(expected.getObjetId()))
            .satisfies(a -> assertThat(a.getCorrelationId()).as("check correlationId").isEqualTo(expected.getCorrelationId()))
            .satisfies(a -> assertThat(a.getDateAction()).as("check dateAction").isEqualTo(expected.getDateAction()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJournalAuditUpdatableRelationshipsEquals(JournalAudit expected, JournalAudit actual) {
        // empty method
    }
}
