package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PartenaireAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartenaireAllPropertiesEquals(Partenaire expected, Partenaire actual) {
        assertPartenaireAutoGeneratedPropertiesEquals(expected, actual);
        assertPartenaireAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartenaireAllUpdatablePropertiesEquals(Partenaire expected, Partenaire actual) {
        assertPartenaireUpdatableFieldsEquals(expected, actual);
        assertPartenaireUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartenaireAutoGeneratedPropertiesEquals(Partenaire expected, Partenaire actual) {
        assertThat(actual)
            .as("Verify Partenaire auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartenaireUpdatableFieldsEquals(Partenaire expected, Partenaire actual) {
        assertThat(actual)
            .as("Verify Partenaire relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartenaireUpdatableRelationshipsEquals(Partenaire expected, Partenaire actual) {
        // empty method
    }
}
