package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PartenaireZoneAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartenaireZoneAllPropertiesEquals(PartenaireZone expected, PartenaireZone actual) {
        assertPartenaireZoneAutoGeneratedPropertiesEquals(expected, actual);
        assertPartenaireZoneAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartenaireZoneAllUpdatablePropertiesEquals(PartenaireZone expected, PartenaireZone actual) {
        assertPartenaireZoneUpdatableFieldsEquals(expected, actual);
        assertPartenaireZoneUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartenaireZoneAutoGeneratedPropertiesEquals(PartenaireZone expected, PartenaireZone actual) {
        assertThat(actual)
            .as("Verify PartenaireZone auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartenaireZoneUpdatableFieldsEquals(PartenaireZone expected, PartenaireZone actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartenaireZoneUpdatableRelationshipsEquals(PartenaireZone expected, PartenaireZone actual) {
        assertThat(actual)
            .as("Verify PartenaireZone relationships")
            .satisfies(a -> assertThat(a.getPartenaire()).as("check partenaire").isEqualTo(expected.getPartenaire()))
            .satisfies(a -> assertThat(a.getZone()).as("check zone").isEqualTo(expected.getZone()));
    }
}
