package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PrestationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrestationAllPropertiesEquals(Prestation expected, Prestation actual) {
        assertPrestationAutoGeneratedPropertiesEquals(expected, actual);
        assertPrestationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrestationAllUpdatablePropertiesEquals(Prestation expected, Prestation actual) {
        assertPrestationUpdatableFieldsEquals(expected, actual);
        assertPrestationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrestationAutoGeneratedPropertiesEquals(Prestation expected, Prestation actual) {
        assertThat(actual)
            .as("Verify Prestation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrestationUpdatableFieldsEquals(Prestation expected, Prestation actual) {
        assertThat(actual)
            .as("Verify Prestation relevant properties")
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFin()).as("check dateFin").isEqualTo(expected.getDateFin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrestationUpdatableRelationshipsEquals(Prestation expected, Prestation actual) {
        assertThat(actual)
            .as("Verify Prestation relationships")
            .satisfies(a -> assertThat(a.getDemande()).as("check demande").isEqualTo(expected.getDemande()))
            .satisfies(a -> assertThat(a.getPartenaire()).as("check partenaire").isEqualTo(expected.getPartenaire()));
    }
}
