package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static sn.orange.conciergerie.domain.AssertUtils.bigDecimalCompareTo;

public class QuotaDetailAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotaDetailAllPropertiesEquals(QuotaDetail expected, QuotaDetail actual) {
        assertQuotaDetailAutoGeneratedPropertiesEquals(expected, actual);
        assertQuotaDetailAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotaDetailAllUpdatablePropertiesEquals(QuotaDetail expected, QuotaDetail actual) {
        assertQuotaDetailUpdatableFieldsEquals(expected, actual);
        assertQuotaDetailUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotaDetailAutoGeneratedPropertiesEquals(QuotaDetail expected, QuotaDetail actual) {
        assertThat(actual)
            .as("Verify QuotaDetail auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotaDetailUpdatableFieldsEquals(QuotaDetail expected, QuotaDetail actual) {
        assertThat(actual)
            .as("Verify QuotaDetail relevant properties")
            .satisfies(a ->
                assertThat(a.getLimite()).as("check limite").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLimite())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotaDetailUpdatableRelationshipsEquals(QuotaDetail expected, QuotaDetail actual) {
        assertThat(actual)
            .as("Verify QuotaDetail relationships")
            .satisfies(a -> assertThat(a.getQuotaService()).as("check quotaService").isEqualTo(expected.getQuotaService()))
            .satisfies(a -> assertThat(a.getZone()).as("check zone").isEqualTo(expected.getZone()));
    }
}
