package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static sn.orange.conciergerie.domain.AssertUtils.bigDecimalCompareTo;

public class QuotaServiceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotaServiceAllPropertiesEquals(QuotaService expected, QuotaService actual) {
        assertQuotaServiceAutoGeneratedPropertiesEquals(expected, actual);
        assertQuotaServiceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotaServiceAllUpdatablePropertiesEquals(QuotaService expected, QuotaService actual) {
        assertQuotaServiceUpdatableFieldsEquals(expected, actual);
        assertQuotaServiceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotaServiceAutoGeneratedPropertiesEquals(QuotaService expected, QuotaService actual) {
        assertThat(actual)
            .as("Verify QuotaService auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotaServiceUpdatableFieldsEquals(QuotaService expected, QuotaService actual) {
        assertThat(actual)
            .as("Verify QuotaService relevant properties")
            .satisfies(a ->
                assertThat(a.getLimite()).as("check limite").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLimite())
            )
            .satisfies(a -> assertThat(a.getUnite()).as("check unite").isEqualTo(expected.getUnite()))
            .satisfies(a -> assertThat(a.getPeriode()).as("check periode").isEqualTo(expected.getPeriode()))
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFin()).as("check dateFin").isEqualTo(expected.getDateFin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuotaServiceUpdatableRelationshipsEquals(QuotaService expected, QuotaService actual) {
        assertThat(actual)
            .as("Verify QuotaService relationships")
            .satisfies(a ->
                assertThat(a.getEligibiliteService()).as("check eligibiliteService").isEqualTo(expected.getEligibiliteService())
            );
    }
}
