package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SegmentClientAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSegmentClientAllPropertiesEquals(SegmentClient expected, SegmentClient actual) {
        assertSegmentClientAutoGeneratedPropertiesEquals(expected, actual);
        assertSegmentClientAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSegmentClientAllUpdatablePropertiesEquals(SegmentClient expected, SegmentClient actual) {
        assertSegmentClientUpdatableFieldsEquals(expected, actual);
        assertSegmentClientUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSegmentClientAutoGeneratedPropertiesEquals(SegmentClient expected, SegmentClient actual) {
        assertThat(actual)
            .as("Verify SegmentClient auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSegmentClientUpdatableFieldsEquals(SegmentClient expected, SegmentClient actual) {
        assertThat(actual)
            .as("Verify SegmentClient relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSegmentClientUpdatableRelationshipsEquals(SegmentClient expected, SegmentClient actual) {
        // empty method
    }
}
