package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ServiceConciergerieAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceConciergerieAllPropertiesEquals(ServiceConciergerie expected, ServiceConciergerie actual) {
        assertServiceConciergerieAutoGeneratedPropertiesEquals(expected, actual);
        assertServiceConciergerieAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceConciergerieAllUpdatablePropertiesEquals(ServiceConciergerie expected, ServiceConciergerie actual) {
        assertServiceConciergerieUpdatableFieldsEquals(expected, actual);
        assertServiceConciergerieUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceConciergerieAutoGeneratedPropertiesEquals(ServiceConciergerie expected, ServiceConciergerie actual) {
        assertThat(actual)
            .as("Verify ServiceConciergerie auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceConciergerieUpdatableFieldsEquals(ServiceConciergerie expected, ServiceConciergerie actual) {
        assertThat(actual)
            .as("Verify ServiceConciergerie relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceConciergerieUpdatableRelationshipsEquals(ServiceConciergerie expected, ServiceConciergerie actual) {
        assertThat(actual)
            .as("Verify ServiceConciergerie relationships")
            .satisfies(a -> assertThat(a.getTypeService()).as("check typeService").isEqualTo(expected.getTypeService()));
    }
}
