package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StatutDemandeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatutDemandeAllPropertiesEquals(StatutDemande expected, StatutDemande actual) {
        assertStatutDemandeAutoGeneratedPropertiesEquals(expected, actual);
        assertStatutDemandeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatutDemandeAllUpdatablePropertiesEquals(StatutDemande expected, StatutDemande actual) {
        assertStatutDemandeUpdatableFieldsEquals(expected, actual);
        assertStatutDemandeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatutDemandeAutoGeneratedPropertiesEquals(StatutDemande expected, StatutDemande actual) {
        assertThat(actual)
            .as("Verify StatutDemande auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatutDemandeUpdatableFieldsEquals(StatutDemande expected, StatutDemande actual) {
        assertThat(actual)
            .as("Verify StatutDemande relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatutDemandeUpdatableRelationshipsEquals(StatutDemande expected, StatutDemande actual) {
        // empty method
    }
}
