package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static sn.orange.conciergerie.domain.AssertUtils.bigDecimalCompareTo;

public class TransactionPaiementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionPaiementAllPropertiesEquals(TransactionPaiement expected, TransactionPaiement actual) {
        assertTransactionPaiementAutoGeneratedPropertiesEquals(expected, actual);
        assertTransactionPaiementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionPaiementAllUpdatablePropertiesEquals(TransactionPaiement expected, TransactionPaiement actual) {
        assertTransactionPaiementUpdatableFieldsEquals(expected, actual);
        assertTransactionPaiementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionPaiementAutoGeneratedPropertiesEquals(TransactionPaiement expected, TransactionPaiement actual) {
        assertThat(actual)
            .as("Verify TransactionPaiement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionPaiementUpdatableFieldsEquals(TransactionPaiement expected, TransactionPaiement actual) {
        assertThat(actual)
            .as("Verify TransactionPaiement relevant properties")
            .satisfies(a ->
                assertThat(a.getMontant()).as("check montant").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMontant())
            )
            .satisfies(a -> assertThat(a.getModePaiement()).as("check modePaiement").isEqualTo(expected.getModePaiement()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getReferenceExterne()).as("check referenceExterne").isEqualTo(expected.getReferenceExterne()))
            .satisfies(a -> assertThat(a.getDateTransaction()).as("check dateTransaction").isEqualTo(expected.getDateTransaction()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionPaiementUpdatableRelationshipsEquals(TransactionPaiement expected, TransactionPaiement actual) {
        assertThat(actual)
            .as("Verify TransactionPaiement relationships")
            .satisfies(a -> assertThat(a.getDemande()).as("check demande").isEqualTo(expected.getDemande()));
    }
}
