package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TypeDemandeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeDemandeAllPropertiesEquals(TypeDemande expected, TypeDemande actual) {
        assertTypeDemandeAutoGeneratedPropertiesEquals(expected, actual);
        assertTypeDemandeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeDemandeAllUpdatablePropertiesEquals(TypeDemande expected, TypeDemande actual) {
        assertTypeDemandeUpdatableFieldsEquals(expected, actual);
        assertTypeDemandeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeDemandeAutoGeneratedPropertiesEquals(TypeDemande expected, TypeDemande actual) {
        assertThat(actual)
            .as("Verify TypeDemande auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeDemandeUpdatableFieldsEquals(TypeDemande expected, TypeDemande actual) {
        assertThat(actual)
            .as("Verify TypeDemande relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeDemandeUpdatableRelationshipsEquals(TypeDemande expected, TypeDemande actual) {
        // empty method
    }
}
