package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UtilisationCodeQrAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtilisationCodeQrAllPropertiesEquals(UtilisationCodeQr expected, UtilisationCodeQr actual) {
        assertUtilisationCodeQrAutoGeneratedPropertiesEquals(expected, actual);
        assertUtilisationCodeQrAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtilisationCodeQrAllUpdatablePropertiesEquals(UtilisationCodeQr expected, UtilisationCodeQr actual) {
        assertUtilisationCodeQrUpdatableFieldsEquals(expected, actual);
        assertUtilisationCodeQrUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtilisationCodeQrAutoGeneratedPropertiesEquals(UtilisationCodeQr expected, UtilisationCodeQr actual) {
        assertThat(actual)
            .as("Verify UtilisationCodeQr auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtilisationCodeQrUpdatableFieldsEquals(UtilisationCodeQr expected, UtilisationCodeQr actual) {
        assertThat(actual)
            .as("Verify UtilisationCodeQr relevant properties")
            .satisfies(a -> assertThat(a.getDateUtilisation()).as("check dateUtilisation").isEqualTo(expected.getDateUtilisation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtilisationCodeQrUpdatableRelationshipsEquals(UtilisationCodeQr expected, UtilisationCodeQr actual) {
        assertThat(actual)
            .as("Verify UtilisationCodeQr relationships")
            .satisfies(a -> assertThat(a.getCodeQrService()).as("check codeQrService").isEqualTo(expected.getCodeQrService()))
            .satisfies(a -> assertThat(a.getPartenaire()).as("check partenaire").isEqualTo(expected.getPartenaire()));
    }
}
