package sn.orange.conciergerie.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ZoneAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertZoneAllPropertiesEquals(Zone expected, Zone actual) {
        assertZoneAutoGeneratedPropertiesEquals(expected, actual);
        assertZoneAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertZoneAllUpdatablePropertiesEquals(Zone expected, Zone actual) {
        assertZoneUpdatableFieldsEquals(expected, actual);
        assertZoneUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertZoneAutoGeneratedPropertiesEquals(Zone expected, Zone actual) {
        assertThat(actual)
            .as("Verify Zone auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertZoneUpdatableFieldsEquals(Zone expected, Zone actual) {
        assertThat(actual)
            .as("Verify Zone relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertZoneUpdatableRelationshipsEquals(Zone expected, Zone actual) {
        // empty method
    }
}
